config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :products
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home", to:"home#index"
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
    validates :prd_img, :prd_name, :prd_price, :prd_quantity, presence:true
    
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cart_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  # GET /cart_items
  # GET /cart_items.json

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  def test
    @cc = request.query_parameters
  end

  # POST /cart_items
  # POST /cart_items.json
  def create
    @cart_item = CartItem.new(cart_item_params)

    respond_to do |format|
      if @cart_item.save
        return redirect_to "/products"
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully created.' }
        format.json { render :show, status: :created, location: @cart_item }
      else
        format.html { render :new }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item.destroy
    return redirect_to "/"
    respond_to do |format|
      format.html { redirect_to cart_items_url, notice: 'Cart item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_item_params
      params.require(:cart_item).permit(:product_id, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
    def index
        if current_user == nil
            redirect_to "/users/sign_in"
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def test
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    begin
    
      @product.destroy
      respond_to do |format|
        format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    rescue ActiveRecord::InvalidForeignKey => e
      return redirect_to "/cant_del_prd.html"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:prd_name, :prd_price, :prd_quantity, :prd_img)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart_items/_form.html.erb
<%= form_with(model: cart_item, local: true) do |form| %>
  <% if cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cart_items/index.html.erb
<a href='/'>Dashboard</a>

app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<a href='/products'>products</a>

app/views/cart_items/test.html.erb
<form method='post' action='/cart_items/1'>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<input type='hidden' name='_method' value='delete' />
<button>delete</button>
</form>

app/views/home/index.html.erb
 <link href="https://fonts.googleapis.com/css?family=Questrial&display=swap" rel="stylesheet">
 <%= stylesheet_link_tag "application.css" %>
 <script
 src="https://code.jquery.com/jquery-3.4.1.min.js"
 integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
 crossorigin="anonymous"></script>

<div id='nav'>
  welcom <%= current_user.email %> # <%= current_user.id %> - <a class="sbtn" href='/products'>Go to shope</a>
  <form method='POST' action='/users/sign_out'>
  <input type='hidden' name='_method' value='DELETE' />
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <button  id='logout-btn'>Logout</button>
  </form>
</div>

<div id="page-content">
<br/>
<% if current_user.cart_items.length == 0 %>
<h3>You cart is empty :(</h3>
<% end %>
<% if current_user.cart_items.length > 0 %>
<h2>Your cart items</h2>
<br/>
<table class='pink_table'>
<thead>
  <tr>
    <th class="sbtn">Product</th>
    <th>Price</th>
    <th>Delete</th>
  </tr>
</thead>

<tbody>
  <% current_user.cart_items.each do |cart_item| %>
    <tr>
      <td><%= cart_item.product.prd_name %></td>
      <td><%= cart_item.product.prd_price %></td>
      <td>
      <form method='post' action='/cart_items/<%= cart_item.id %>'>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <input type='hidden' name='_method' value='delete' />
      <button class='btns red-btn sbtn'>delete</button>
      </form>
      </td>
    </tr>
  <% end %>
</tbody>
</table>
<% end %>
</div>
  <%= javascript_include_tag "application.js" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyShoppingCart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
    

  <%= javascript_include_tag "application.js" %>
  
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prd_name %>
    <%= form.text_field :prd_name %>
  </div>

  <div class="field">
    <%= form.label :prd_price %>
    <%= form.text_field :prd_price %>
  </div>

  <div class="field">
    <%= form.label :prd_quantity %>
    <%= form.number_field :prd_quantity %>
  </div>
  <div class="field">
  <%= form.label :prd_img %>
  <%= form.text_field :prd_img %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Questrial&display=swap" rel="stylesheet">
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
<%= stylesheet_link_tag "application.css" %>

<div id='nav'>
welcom <%= current_user.email %> # <%= current_user.id %> - <a class="sbtn" href='/'>Dashboard</a>
<form method='POST' action='/users/sign_out'>
<input type='hidden' name='_method' value='DELETE' />
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<button id='logout-btn'>Logout</button>

</form>
</div>


<div id="page-content">
<% if @products.length == 0 %>
This shope has no products
<% end %>
<% if @products.length > 0 %>
<h1>Products</h1>

<div id='products-container'>
  <% @products.each do |product| %>
    <div id='product-card'>
    <div id='prd_name'>
    <%= product.prd_name %>
  </div>
      <img alt='' src='<%= product.prd_img %>' id='prd_img'/>
      <center>
      <div id='prd_price'><%= product.prd_price %> SAR</div>
      <div id='prd_quantity'>
        <%= product.prd_quantity %> Available
      </div>
      </center>
      <form method='POST' action='/cart_items'>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <input type="hidden" name="cart_item[product_id]" id="cart_item_product_id" value='<%= product.id %>' />
      <input type="hidden" name="cart_item[user_id]" id="cart_item_user_id" value='<%= current_user.id %>' />
     <center>
     <button title='<%= product.id %>' id='add_to_cart' class='btns blue-btn'>Add To Cart</button>
     </center>
     
     </form>
     <% if current_user.email == 'nona@gmail.com' %>
     <form method='POST' action='/products/<%= product.id %>'>
     <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type='hidden' name='_method' value='delete' />
    <center>
    <button title='<%= product.id %>' id='add_to_cart' class='btns red-btn'>DELETE</button>
    </center> 
    </form>
    <% end %>
    </div>
  <% end %>
</div>
<% end %>
<%= link_to 'New Product', new_product_path %>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Prd name:</strong>
  <%= @product.prd_name %>
</p>

<p>
  <strong>Prd price:</strong>
  <%= @product.prd_price %>
</p>

<p>
  <strong>Prd quantity:</strong>
  <%= @product.prd_quantity %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>